services:
  transaction-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - postgres
      - kafka
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=localhost;Port=5432;Database=transactions;Username=postgres;Password=postgres
      - Kafka__BootstrapServers=localhost
      - Kafka__Port=9092
